// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/start-client-core";
import { getWebRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { createMockSupabaseClient } from "./client";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      console.warn(
        `[Supabase Middleware] Server keys missing. Bypassing authorization using simulated mock token.`,
      );
      const request = getWebRequest();
      if (!request?.headers) {
        throw new Error("Unauthorized: No request headers available");
      }

      const authHeader = request.headers.get("authorization") || "";
      let userId = "mock-user-123";
      let username = "guest";
      let email = "guest@example.com";

      if (authHeader.startsWith("Bearer ")) {
        const token = authHeader.replace("Bearer ", "");
        if (token && token.includes(":")) {
          const parts = token.split(":");
          userId = parts[0] || userId;
          username = parts[1] || username;
          email = parts[2] || email;
        } else if (token) {
          userId = token;
        }
      }

      const mockSupabase = createMockSupabaseClient();
      return next({
        context: {
          supabase: mockSupabase,
          userId: userId,
          claims: { sub: userId, email: email, user_metadata: { username } },
        },
      });
    }

    const request = getWebRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error("Unauthorized: Invalid token");
    }

    if (!data.claims.sub) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
